# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2842bd69c7e52361b56514b992f37b11d7f5cccc799b13a238a82072130d113c978a9f0f41e22fb43aed0e4398339f80a25ec2f915687d87c34fedc883c2b997

test:
  secret_key_base: 74c12693a60c9cf85b79938def7c565475bd7c88b98279a7ee9721b551d52e9ef7e8502be929aa86614655fcfc32e17a0f92a197b860664ead33ec609a190d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
